type Test = void
type ZZZ = int





type                    OO = boolean

type U = float
   -- s s 
type S =  string   


type Literal = "hello, World"

type EscapedLiteral = "\" \\ \n \r \t"


type Test = optional<null>
