type Test = void
type ZZZ = int





type                    OO = boolean

type U = float
   -- s s 
type S =  string   


type Literal = "hello, World"

type EscapedLiteral = "\" \\ \n \r \t"


type Test = optional<null>


type Test2 = union<Test, U>

type IU = argument<optional<string>>

type Func = function<argument<union<null, number>>, float> 

type Func2 = function<Func, "test"> 
